### ISSUE TITLE
missing asset files 

### ISSUE THREAD

**Issue by Shaunmax** [DaVikingCode/Citrus-Engine-Examples#11]
All the embeded assets files are missing ?

**Comment by alamboley** [comment]
@Shaunmax could you precise please? I don't see what is missing.

**Comment by Shaunmax** [comment]
> @Shaunmax could you precise please? I don't see what is missing.

the `embed` folder is missing 

![image](https://github.com/DaVikingCode/Citrus-Engine-Examples/assets/16576562/ff46917c-4260-4554-85fe-8685cfd76218)

**Comment by alamboley** [comment]
Well, it's at the root: https://github.com/DaVikingCode/Citrus-Engine-Examples/blob/master/embed/dragonbones/DragonWithClothes.png

Depending how is setup your project, maybe you have to change Embed path.

**Comment by Shaunmax** [comment]
> Well, it's at the root: https://github.com/DaVikingCode/Citrus-Engine-Examples/blob/master/embed/dragonbones/DragonWithClothes.png
> 
> Depending how is setup your project, maybe you have to change Embed path.

oops! I am sorry, my bad! it was a project setup issue from my side!

**Comment by alamboley** [comment]
No worries!
